version: 2
updates:
  - package-ecosystem: npm
    directory: /tooling/tree-sitter-w
    schedule:
      interval: monthly
    labels:
      - dependencies
      - tooling
    reviewers:
      - Wallacy
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
    reviewers:
      - Wallacy
