// atlas:begin operators
module atlas_operators

fn operatorSurface(payload: ref any Reflectable) {
  var value = 8
  var other = 2
  var fallback = 1
  var bits = 0
  var registers = [0, 1]

  value = other
  value += other
  value -= other
  value *= other
  value /= other
  value %= other
  value **= other
  value <<= other
  value >>= other
  value &= other
  value ^= other
  value |= other
  registers[index()] <<= 1

  let coalesced = optionalValue ?? fallback
  let logical = ready || pending && enabled
  let bitwise = value | other ^ fallback & bits
  let inspected = value |> normalize() |> inspect() |> render()
  let pipedDecoded = value |> try json.decode<Document>()
  let copied = copy value |> inspect()
  let pipeAfterCoalescing = (optionalValue ?? fallback) |> inspect()
  let coalescingAfterPipe = (value |> inspect()) ?? fallback
  let inverted = ~value
  let equal = value == other
  let related = value < other
  let typed = payload is ReservationKey
  let recovered = payload as? ReservationKey
  let typeIdentity = type of payload
  let staticTypeIdentity = type of ReservationKey
  let staticInfo = info of ReservationKey
  let dynamicInfo = info of payload
  let precedence = type of value == other
  let grouped = type of (value == other)
  let contained = value in 0..<other
  let ranges = 0...other
  // Bounded and one-sided forms include `...` and `..<`.
  // `>..` and `>..<` are current contract spellings with a Tree-sitter witness gap.
  let shifts = value << other >> bits
  let arithmetic = value + other - bits
  let products = value * other / fallback % other @ other
  let power = -2 ** 2
  let chained = source?.field
  let propagated = optionalValue?
  let selected = select(..<other)
  let selectedUpper = select(value...)
  let named = u16.checkedAdd(value, other)
  let checkedSubtract = u16.checkedSubtract(value, other)
  let checkedMultiply = u16.checkedMultiply(value, other)
  let checkedNegate = u16.checkedNegate(value)
  let checkedDivide = u16.checkedDivide(value, other)
  let checkedRemainder = u16.checkedRemainder(value, other)
  let euclideanDividePositive = i32.euclideanDivide(-7, 3)
  let euclideanDivideNegative = i32.euclideanDivide(-7, -3)
  // `euclideanDivide(i32.min, -1)` panics like `/`; the oracle covers this edge.
  let euclideanRemainderPositive = i32.euclideanRemainder(-7, 3)
  let euclideanRemainderNegative = i32.euclideanRemainder(-7, -3)
  let euclideanRemainderEdge = i32.euclideanRemainder(i32.min, -1)
  let checkedPower = u16.checkedPower(value, other)
  let checkedShiftLeft = u16.checkedShiftLeft(value, other)
  let checkedShiftRight = u16.checkedShiftRight(value, other)
  let wrapped = u16.wrappingAdd(value, other)
  let wrappingSubtract = u16.wrappingSubtract(value, other)
  let wrappingMultiply = u16.wrappingMultiply(value, other)
  let wrappingNegate = u16.wrappingNegate(value)
  let wrappingPower = u16.wrappingPower(value, other)
  let wrappingShiftLeft = u16.wrappingShiftLeft(value, other)
  let clipped = u16.saturatingAdd(value, other)
  let saturatingSubtract = u16.saturatingSubtract(value, other)
  let saturatingMultiply = u16.saturatingMultiply(value, other)
  let saturatingNegate = u16.saturatingNegate(value)
  let saturatingPower = u16.saturatingPower(value, other)
  let flagged = u16.overflowingAdd(value, other)
  let overflowingSubtract = u16.overflowingSubtract(value, other)
  let overflowingMultiply = u16.overflowingMultiply(value, other)
  let overflowingNegate = u16.overflowingNegate(value)
  let overflowingPower = u16.overflowingPower(value, other)
  let carry = u16.carryingAdd(value, other)
  let borrow = u16.borrowingSubtract(value, other)
  let full = u16.fullMultiply(value, other)
  let shifted = u16.maskedShiftRight(value, other)
  let maskedShiftLeft = u16.maskedShiftLeft(value, other)
  let logicalShift = u16.logicalShiftRight(value, other)
  let rotated = u16.rotatedLeft(value, other)
  let rotatedRight = u16.rotatedRight(value, other)
  let encoded = value.toBits()
  let decoded = u16.fromBits(encoded)
  let wire = value.toBytes(order: .big)
  let restored = u16.fromBytes(wire, order: .big)
  let bitWidth = u8.bitWidth
  let countOnes = u8.countOnes(value)
  let countZeros = u8.countZeros(value)
  let countLeadingZeros = u8.countLeadingZeros(value)
  let countTrailingZeros = u8.countTrailingZeros(value)
  let reversedBits = u8.reversedBits(value)
  let reversedBytes = u16.reversedBytes(value)

  let _ = coalesced
  let _ = logical
  let _ = bitwise
  let _ = inspected
  let _ = pipedDecoded
  let _ = copied
  let _ = inverted
  let _ = equal
  let _ = related
  let _ = typed
  let _ = recovered
  let _ = typeIdentity
  let _ = staticTypeIdentity
  let _ = staticInfo
  let _ = dynamicInfo
  let _ = precedence
  let _ = grouped
  let _ = contained
  let _ = ranges
  let _ = shifts
  let _ = arithmetic
  let _ = products
  let _ = power
  let _ = chained
  let _ = propagated
  let _ = selected
  let _ = named
  let _ = checkedSubtract
  let _ = checkedMultiply
  let _ = checkedNegate
  let _ = checkedDivide
  let _ = checkedRemainder
  let _ = euclideanDividePositive
  let _ = euclideanDivideNegative
  let _ = euclideanRemainderPositive
  let _ = euclideanRemainderNegative
  let _ = euclideanRemainderEdge
  let _ = checkedPower
  let _ = checkedShiftLeft
  let _ = checkedShiftRight
  let _ = wrapped
  let _ = wrappingSubtract
  let _ = wrappingMultiply
  let _ = wrappingNegate
  let _ = wrappingPower
  let _ = wrappingShiftLeft
  let _ = clipped
  let _ = saturatingSubtract
  let _ = saturatingMultiply
  let _ = saturatingNegate
  let _ = saturatingPower
  let _ = flagged
  let _ = overflowingSubtract
  let _ = overflowingMultiply
  let _ = overflowingNegate
  let _ = overflowingPower
  let _ = carry
  let _ = borrow
  let _ = full
  let _ = shifted
  let _ = maskedShiftLeft
  let _ = logicalShift
  let _ = rotated
  let _ = rotatedRight
  let _ = decoded
  let _ = restored
  let _ = bitWidth
  let _ = countOnes
  let _ = countZeros
  let _ = countLeadingZeros
  let _ = countTrailingZeros
  let _ = reversedBits
  let _ = reversedBytes
}
// atlas:end operators
